AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A random hello world example.

Resources:

  PassMessage:
    Type: AWS::Serverless::Function
    Properties:
      Description: Passes a message to the server
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: lambdas/pass_message/
      Events:
        PassMessage:
          Type: Api
          Properties:
            Method: any
            Path: /message

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt
        - PassMessage
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'

  MyGetMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: GET
        IntegrationResponses:
          -
            StatusCode: 200
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PassMessage.Arn}/invocations
      MethodResponses:
        -
          StatusCode: 200
          ResponseModels:
            application/json: Empty
      ResourceId:
        Ref: MyGetResource
      RestApiId:
        Ref: MyApiGateway
