AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A random hello world example.

Resources:

  PassMessage:
    Type: AWS::Serverless::Function
    Properties:
      Description: Passes a message to the server
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: lambdas/pass_message/
      Events:
        PassMessage:
          Type: Api
          Properties:
            Method: any
            Path: /message
