AWSTemplateFormatVersion: '2010-09-09'
Description: A random hello world example.
Resources:
  PassMessage:
    Properties:
      CodeUri: s3://paolo-hello-world/971b89193221412ea22d1c99b08846fa
      Description: Passes a message to the server
      Events:
        PassMessage:
          Properties:
            Method: any
            Path: /message
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
